name: SkyWarsLobby
version: ${project.version}
main: com.ultimismc.skywars.lobby.SkyWarsLobbyPlugin
depend: [ PlaceholderAPI, LuckPerms ]
authors: [ DirectPlan ]
description: A custom skywars lobby plugin developed for the UltimisMC Network
