name: UltSkyWars
version: ${project.version}
main: com.ultimismc.skywars.core.SkyWarsPlugin
depend: [ WorldEdit, PlaceholderAPI, LuckPerms ]
authors: [ DirectPlan ]
description: A custom skywars plugin developed for the UltimisMC Network
